sudo: enabled
matrix:
  include:
  - if: tag =~ .+
    os: windows
    language: sh
    env: x86_64=true pyver=3.5
#  - if: tag =~ .+
#    os: windows
#    language: sh
#    env: x86_32=true pyver=3.5
#  - if: tag =~ .+
#    os: linux
#    dist: xenial
#    language: python
#    python: '3.5'
  - if: NOT tag =~ .+
    os: linux
    language: cpp
    compiler:
      - gcc
before_install:
- if [[ -z $TRAVIS_TAG ]]; then
    sudo add-apt-repository -y ppa:deadsnakes/ppa;
    sudo apt-get update;
  elif [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'windows' ]] && [[ $pyver == '3.5' ]] && [[ $x86_64 == 'true' ]];
    choco install -y python3 --version 3.5.4;
    export PATH="/c/Python35:/c/Python35/Scripts:$PATH";
    python -m pip install --upgrade pip wheel;
  elif [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'windows' ]] && [[ $pyver == '3.5' ]] && [[ $x86_32 == 'true' ]];
    choco install -y python3 --version 3.5.4 --x86;
    export PATH="/c/Python35:/c/Python35/Scripts:$PATH";
    python -m pip install --upgrade pip wheel;
  elif [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'windows' ]] && [[ $pyver == '3.6' ]] && [[ $x86_64 == 'true' ]];
    choco install -y python3 --version 3.6.8;
    export PATH="/c/Python36:/c/Python36/Scripts:$PATH";
    python -m pip install --upgrade pip wheel;
  elif [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'windows' ]] && [[ $pyver == '3.6' ]] && [[ $x86_32 == 'true' ]];
    choco install -y python3 --version 3.6.8 --x86;
    export PATH="/c/Python36:/c/Python36/Scripts:$PATH";
    python -m pip install --upgrade pip wheel;
  elif [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'windows' ]] && [[ $pyver == '3.7' ]] && [[ $x86_64 == 'true' ]];
    choco install -y python3 --version 3.7.1;
    export PATH="/c/Python37:/c/Python37/Scripts:$PATH";
    python -m pip install --upgrade pip wheel;
  elif [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'windows' ]] && [[ $pyver == '3.7' ]] && [[ $x86_32 == 'true' ]];
    choco install -y python3 --version 3.7.1 --x86;
    export PATH="/c/Python37:/c/Python37/Scripts:$PATH";
    python -m pip install --upgrade pip wheel;
  else
    echo "Unknown conditions";
    exit 2;
  fi
install:
- if [[ -z $TRAVIS_TAG ]]; then
    sudo apt-get install python3.6;
    sudo apt-get install python3.6-dev;
    sudo apt-get install libgmp3-dev;
    sudo apt-get install valgrind;
    wget https://bootstrap.pypa.io/get-pip.py;
    sudo python3.6 get-pip.py;
  fi
script:
- if [[ -z $TRAVIS_TAG ]]; then
    mkdir build;
    cd build;
    cmake ../;
    cmake --build . -- -j 6;
    ./src/runtest;
    valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all  ./src/runtest;
    cd ../;
    virtualenv -p python3.6 bls;
    source bls/bin/activate;
    pip3 install .;
    python3.6 ./python-bindings/test.py;
  else
    git submodule update --init --recursive;
    python setup.py bdist_wheel;
    ls -l dist;
  fi
