sudo: enabled
matrix:
  include:
  - if: tag =~ .+
    os: windows
    language: sh
    env: x86_64=true py=3.5
#  - if: tag =~ .+
#    os: windows
#    language: sh
#    env: x86_32=true py=3.5
#  - if: tag =~ .+
#    os: linux
#    dist: xenial
#    language: python
#    python: '3.5'
  - if: NOT tag =~ .+
    os: linux
    language: cpp
    compiler:
      - gcc
before_install:
- if [[ -z $TRAVIS_TAG ]]; then
    sudo add-apt-repository -y ppa:deadsnakes/ppa;
    sudo apt-get update;
  fi
install:
- if [[ -z $TRAVIS_TAG ]]; then
    sudo apt-get install python3.6;
    sudo apt-get install python3.6-dev;
    sudo apt-get install libgmp3-dev;
    sudo apt-get install valgrind;
    wget https://bootstrap.pypa.io/get-pip.py;
    sudo python3.6 get-pip.py;
  fi
script:
- if [[ -z $TRAVIS_TAG ]]; then
    mkdir build;
    cd build;
    cmake ../;
    cmake --build . -- -j 6;
    ./src/runtest;
    valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all  ./src/runtest;
    cd ../;
    virtualenv -p python3.6 bls;
    source bls/bin/activate;
    pip3 install .;
    python3.6 ./python-bindings/test.py;
  fi
