language: sh
os: windows
compiler: gcc
before_install:
choco install -y python3 --version 3.6.8;
export PATH="/c/Python36:/c/Python36/Scripts:$PATH";
python -m pip install --upgrade pip wheel;
python -m pip install blspy
